Repository gardener/logging, pull requests merged in 2020-06, with the labels that each got.

#34 Update CODEOWNERS
  CODEOWNERS
  fluentd-es/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm

#36 Repair ci publish tast
  Makefile
  README.md
  fluent-bit-to-loki/Dockerfile
  fluent-bit-to-loki/Makefile
Labels: needs/ok-to-test, reviewed/lgtm

#35 Add move self explaned information aboult fluent-bit to Loki plugin
  README.md
Labels: needs/ok-to-test

#37 remove ialidzhikov and vpnachev from codeowners
  CODEOWNERS
Labels: needs/ok-to-test, reviewed/lgtm

#38 repait the publish CI task to make and push fluent-bit-to-loki images
  fluent-bit-to-loki/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test

#40 fix fluent-bit-to-loki build path
  Makefile
  fluent-bit-to-loki/Dockerfile
Labels: reviewed/lgtm, reviewed/ok-to-test

#41 add verify ci task
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm

#43 fix the fluent-bit-to-loki plugin build path
  fluent-bit-to-loki/Dockerfile
Labels: reviewed/lgtm, reviewed/ok-to-test

#46 remove fluent-bit golang lint check
  .ci/check
  fluent-bit-to-loki/.golangci.yaml
  fluent-bit-to-loki/cmd/out_loki.go
Labels: reviewed/lgtm, reviewed/ok-to-test
