Repository gardener/logging, pull requests merged in 2021-01, with the labels that each got.

#83 make the batch ID number configurable and some refactoring
  README.md
  cmd/out_loki.go
  example.config
  pkg/batch/batch.go
  pkg/batch/batch_test.go
  pkg/buffer/dque.go
  pkg/client/client.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/lokiplugin/loki.go
  pkg/lokiplugin/loki_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#84 Update PR template
  .github/pull_request_template.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#88 Move forwarded_log counter to the end of the plugin and add IncomingL…
  pkg/client/client.go
  pkg/lokiplugin/loki.go
  pkg/metrics/metrics.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s
