Repository gardener/logging, pull requests merged in 2022-08, with the labels that each got.

#135 Add GOARCH in the go build commands
  Dockerfile
  Makefile
Labels: kind/bug, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging

#136 Add GOARCH env on fluent-bit-loki-plugin
  Makefile
Labels: kind/bug, needs/review, size/xs, reviewed/ok-to-test, area/logging

#133 Fix some issues with the event logger.
  .dockerignore
  Dockerfile
  Makefile
  hack/get-build-ld-flags.sh
  hack/install.sh
  pkg/events/events_logger.go
  pkg/events/types.go
Labels: kind/enhancement, needs/review, needs/rebase, needs/ok-to-test, needs/second-opinion, size/l, area/logging

#137 Update base images
  Dockerfile
Labels: needs/review, size/xs, needs/ok-to-test, area/logging, kind/technical-debt

#139 Add unit test for sorted client
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/fake_client.go
  pkg/client/sorted_client.go
  pkg/client/sorted_client_test.go
Labels: needs/ok-to-test, kind/test, reviewed/lgtm, size/l, area/logging

#142 Make able event-logger to watch events in multiple namespace specified by flag
  cmd/event-logger/app/options.go
  pkg/events/events_logger.go
  pkg/events/gardener_event_watcher.go
  pkg/events/options.go
  pkg/events/types.go
Labels: kind/enhancement, needs/ok-to-test, size/m, reviewed/lgtm, area/logging

#145 Revert the building of multiarch images
  .ci/pipeline_definitions
Labels: kind/bug, needs/review, size/xs, needs/ok-to-test, area/logging

#144 Always clone the label set in multitenant client befor sending the logs to the next client
  pkg/client/multi_tenant_client.go
Labels: kind/bug, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging

#146 Upgrade Docker images due to compliance reasons
  Dockerfile
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging

#147 Remove __gardener_multitenant_id__ when it is not needed
  pkg/client/client.go
  pkg/client/multi_tenant_client.go
  pkg/client/multi_tenant_client_test.go
Labels: kind/enhancement, needs/ok-to-test, size/m, reviewed/lgtm, area/logging

#148 Set the name of the batch ID label from the pluging configuration
  README.md
  cmd/fluent-bit-loki-plugin/out_loki.go
  pkg/batch/batch.go
  pkg/batch/batch_test.go
  pkg/client/sorted_client.go
  pkg/client/sorted_client_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/enhancement, needs/ok-to-test, size/m, reviewed/lgtm, area/logging

#149 Address some todos
  hack/install-requirements.sh
  pkg/buffer/dque.go
  pkg/events/options.go
  pkg/lokiplugin/loki.go
  vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/component-base/logs/logs.go
  vendor/modules.txt
Labels: size/s, needs/ok-to-test, reviewed/lgtm, area/logging, kind/cleanup

#150 Fix the fix
  cmd/event-logger/app/options.go
  pkg/events/gardener_event_watcher.go
  pkg/events/options.go
Labels: kind/bug, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging
