Repository gardener/logging, pull requests merged in 2023-05, with the labels that each got.

#190 bump up golang image build version from 1.20.2 to 1.20.4
  Dockerfile
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging

#189 support multi-platform container image builds
  .gitignore
  Dockerfile
  Makefile
  hack/docker-image-build.sh
  hack/docker-image-push.sh
  hack/install-requirements.sh
Labels: needs/ok-to-test, size/m, reviewed/lgtm, area/logging

#193 Bump semver patch on the next release
  .ci/pipeline_definitions
Labels: needs/review, size/xs, area/logging

#195 Fix frequent cluster updates
  pkg/buffer/buffer_suit_test.go
  pkg/client/buffer.go
  pkg/client/buffer_client.go
  pkg/client/buffer_test.go
  pkg/client/client.go
  pkg/client/dque.go
  pkg/client/fake_client.go
  pkg/client/metric_promtail_client.go
  pkg/client/multi_tenant_client.go
  pkg/client/multi_tenant_client_test.go
  pkg/client/pack_client.go
  pkg/client/pack_client_test.go
  pkg/client/sorted_client.go
  pkg/client/sorted_client_test.go
  pkg/client/types.go
  pkg/controller/client.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/types/valiclient.go
  pkg/valiplugin/vali.go
  pkg/valiplugin/vali_test.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l, area/logging
