Repository gardener/logging, pull requests merged in 2023-06, with the labels that each got.

#201 update alpine base image to 3.18.0
  Dockerfile
Labels: needs/review, size/xs, needs/ok-to-test, kind/task, reviewed/lgtm, area/logging

#203 Set responsibles
  .ci/pipeline_definitions
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test, area/logging

#202 add skaffold support for fluent-bit-plugin
  Makefile
  docs/development/images/skaffold.png
  docs/development/skaffold.md
  hack/.includes.sh
  hack/load-container-images.sh
  hack/run-skaffold.sh
  hack/test-e2e-local.sh
  hack/update_chart_images.sh
  skaffold.env
  skaffold.yaml
Labels: needs/changes, needs/review, needs/ok-to-test, needs/second-opinion, kind/test, size/l, area/logging

#205 adapt fluent-bit-vali-plugin to log metadata
  cmd/fluent-bit-vali-plugin/out_vali.go
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging

#207 Init Cluster informer only when DynamicHostPath is set
  cmd/fluent-bit-vali-plugin/out_vali.go
  pkg/valiplugin/vali.go
Labels: kind/enhancement, size/s, needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test, area/logging
