Repository gardener/logging, pull requests merged in 2025-01, with the labels that each got.

#282 build: bump up golang to 1.23.5
  Dockerfile
  go.mod
Labels: needs/ok-to-test

#285 build: bump up vali to the latest released version
  go.mod
  go.sum
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test, area/logging

#287 fix: add libeconf libs for tune2fs container image
  Dockerfile
Labels: size/xs, needs/ok-to-test, reviewed/lgtm, area/logging
