Repository gardener/logging, pull requests merged in 2025-03, with the labels that each got.

#299 Update go to 1.24.1
  Dockerfile
  go.mod
Labels: kind/enhancement, needs/review, size/xs, needs/ok-to-test, area/logging

#300 build: fix missed verify step in .ci
  .ci/verify
Labels: kind/bug, needs/review, size/xs, needs/ok-to-test, area/logging

#303 Observability 2.0
  docs/images/Observability 2.0.png
  docs/observability-2.0/Observability 2.0.md
Labels: kind/enhancement, size/m, reviewed/lgtm, reviewed/ok-to-test, area/logging

#305 Fix indentation of example
  docs/observability-2.0/Observability 2.0.md
Labels: kind/enhancement, size/xs, needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test, area/logging

#306 Explicitly mention and Garden and Seeds are in the scope of Observability v2.0 and fix few typos
  docs/observability-2.0/Observability 2.0.md
Labels: kind/enhancement, needs/review, size/xs, needs/ok-to-test, reviewed/lgtm, area/logging
